-- This was automatically generated by stack; I may at some point write some
-- proper tests but for now this will stay here as an artifact of stack.

main :: IO ()
main = putStrLn "Test suite not yet implemented"
